/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : qatar

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2017-02-27 01:21:24
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for listings
-- ----------------------------
DROP TABLE IF EXISTS `listings`;
CREATE TABLE `listings` (
  `id` mediumint(9) NOT NULL,
  `roll-over-description-english` varchar(150) DEFAULT NULL,
  `roll-over-description-arabic` varchar(150) DEFAULT NULL,
  `full-description-english` mediumtext,
  `full-description-arabic` mediumtext,
  `location` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of listings
-- ----------------------------
INSERT INTO `listings` VALUES ('0', null, 'انظر في أعماق التاريخ.\r\n\r\nستراتفورد أبون آفون', 'Immerse yourself in everything Shakespeare in Stratford-upon-Avon. Built on the banks of the Avon River is best known as the birthplace of William Shakespeare and is subsequently the home of The Royal Shakespeare Company.', null, 'BIRMINGHAM');
INSERT INTO `listings` VALUES ('1', 'Curious countryside cottages. \r\n\r\nCotswolds.', 'بيوت ريفية صغيرة رائعة. \r\n\r\nكوتسوولدز (Cotswolds).', 'Explore villages made of honey-coloured stone and see why this area is picture-postcard England at its most enchanting. It\'s a favourite getaway for British celebrities so excellent food and luxury places to stay abound. Be sure to enjoy a picnic by the brook in Castle Combe, one of Britain\'s prettiest villages.', '', 'BIRMINGHAM');
INSERT INTO `listings` VALUES ('3', 'Fields of bluebells.\r\n\r\nWarwickshire.', 'حقول الجريس\r\n\r\nوورويكشاير', 'Visit Warwickshire to revel in the heart of Shakespeare\'s England. See signature motte-and-bailey forts and romantic Elizabethan architecture. Miles of canals and stairway locks beckon you for lazy lunches and picnics. A visit in springtime will almost certainly guarantee the pleasure of seeing carpets of delicately scented bluebells throughout ancient woodlands.', '', 'BIRMINGHAM');
INSERT INTO `listings` VALUES ('4', 'Beautiful blossom. \r\nBatsford Arboretum, Gloucestershire.', 'زهور جميلة \r\nمشتل باتسفورد، جلوسيسترشاير', 'Elegant spa and market towns and stately homes presiding over rolling, green landscapes are a plenty in Gloucestershire. However, Batsford Arboretum is a must see for nature lovers and is home to a whole host of flora and fauna. There is a lovely annual programme of events – from outdoor theatre productions under the arboretum tree canopy to gardening themed talks and special events.', '', 'BIRMINGHAM');
INSERT INTO `listings` VALUES ('5', 'Be enchanted by Festival No. 6.\r\nPortmeirion', 'استمتع بسحر المهرجان رقم 6 (FESTIVAL No.6)\r\nبورتميريون', 'You\'ll be forgiven for wondering if you\'re in Britain when you arrive in Portmeirion. With its cliff-top location and Italianate white-washed buildings, it\'s often compared to a Mediterranean village, but the spectacular coastal views are 100% Welsh. Visit when Festival No 6 is on and see comedy shows, film previews and some of the most exciting musicians from around the world.', '', 'BIRMINGHAM');
INSERT INTO `listings` VALUES ('6', 'A view worth every step.\r\n\r\nEdinburgh. ', 'هناك مشهد يستحق الإطلالة عليه في كل خطوة.\r\n\r\nإدنبره ', 'The capital of Scotland makes an unforgettable impression with its historic, hilly landscape. Before you head out to the beautiful landscapes of Scotland’s countryside, spend the day in its capital city, Edinburgh. It’s known for its world-class festivals and the cityscapes of its Old and New Towns form a UNESCO World Heritage site. There’s plenty of green space within the city too; at its heart is Holyrood Park with three lochs, wildlife and Arthur’s Seat, an extinct volcano, to explore. The Royal Botanic Garden is another green oasis in the city.', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('7', 'Steaming across 21 arches of magical history.\r\n\r\nGlenfinnan Viaduct', null, 'For a truly magical experience, board the legendary Jacobite Steam Train and chug across the world-famous 21-arched Glenfinnan Viaduct and through some of the most beautiful and storied countryside in the world. The area is renowned for its beauty as well as its historic significance. \r\n\r\nFor a truly magical experience, board the legendary Jacobite Steam Train and chug across the world-famous 21-arched Glenfinnan Viaduct and through some of the most beautiful and storied countryside in the world. The area is renowned for its beauty as well as its historic significance.', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('8', 'The land of myths and legends.\r\n\r\nEilean Donan Castle', 'أرض الأساطير والخرافات.\r\n\r\nقلعة إيليان دونان', 'You won’t be able to stop gazing out of the windows if you stay in the luxurious Eilean Donan Cottage. It has uninterrupted views across the water to a sight you’ll more than likely already recognise: the 13th-century Eilean Donan castle, standing on an island where three sea lochs meet and connected to the shore by a stern stone bridge. It’s one of the most iconic images of Scotland.', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('9', 'A view worth every step.\r\n\r\nEdinburgh.', 'مغامرات أعلى الأشجار. \r\n\r\nغابة جلينتريس', 'Climb to the highest point in the city. The reward as you stand at the top of 244 metre Arthur’s Seat after a hike through Holyrood Park is the sight of Edinburgh’s castle, crescents and spires mapped out all around you, and beyond to the Forth Bridge, the east coast and the Highlands. Pick up a picnic from one of Edinburgh’s fine food delis for the journey. ', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('10', 'Treetop adventures. \r\n\r\nGlentress Forest', null, 'Looking for some active fun? Designed to entertain tarzans big and small, expect to traverse the tree canopy on zip wires and aerial walkways. At Go Ape, explore the forest from high up on a Tree Top Adventure – swing through the trees, zoom down zip wires and tackle high rope crossings whilst enjoying the amazing views of one of Scotland’s amazing natural environments. ', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('11', 'Attempt archery in the great outdoors.\r\nScottish Highlands', null, 'You’ll require both skill and a steady hand to strike gold in this fun field sport. Archery is an ancient and elegant pastime which is a ‘must do’ activity for everybody for some friendly competition. Prepare your bow and arrow, pull back and shoot all whilst testing your hand-to-eye coordination as you practice and develop your ability.', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('12', 'Scenery to take your breath away. Loch Ness, Inverness', null, 'There are many fantastic facts, stories and legends about Loch Ness: it holds more fresh water than all the lakes in England and Wales combined; its waters never freeze over; and it’s the home of the Loch Ness Monster. It’s also incredibly beautiful, so take a moment to simply take in the views. By foot or by boat, the possibilities for adventure around Inverness and Loch Ness are never-ending.', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('13', 'Hear the band in full swing.\r\n\r\nEdinburgh', 'استمع إلى الفرقة الموسيقية في قمة أدائها. \r\n\r\nإدنبره', 'Bringing together grand spectacle, fantastic music and Scottish heritage, the annual Royal Military Tattoo at Edinburgh Castle is a major summer event showcasing some of the best traditional and military drumming and piping around. There are bands with polished trumpets and crisp uniforms, cultural dance troupes, singers, and a grand display of fireworks at the end of every Saturday performance. ', '', 'EDINBURGH');
INSERT INTO `listings` VALUES ('14', 'Make a splash in the city. \r\n\r\nLondon.', 'استمتع بالألعاب المائية في المدينة. \r\n\r\nلندن.', 'In London you can marvel at the city’s many iconic buildings and palaces, immerse yourself in culture at one of the 170 museums and relax amidst the natural beauty of the Royal Parks. Take a spin on the London Eye to experience spectacular views of the city\'s skyline and get a unique perspective on iconic London landmarks like Big Ben and Westminster Abbey.', '', 'LONDON');
INSERT INTO `listings` VALUES ('15', 'Discover theatre in the Queen’s Gardens. \r\n\r\nLondon.', 'استكشف المسرح في حدائق الملكة. \r\n\r\nلندن.', 'Did you know there are more than 230 theatres in London? Watch a musical in the West End or try something different and head to one of the few outdoor theatres such as Regent’s Park Open Air Theatre. Established in 1932, it is one of the largest theatres in London and hosts an extensive run of summertime plays under the stars.  ', '', 'LONDON');
INSERT INTO `listings` VALUES ('16', 'Rush Hour at the Palace.\r\n\r\nWindsor', 'ساعة الذروة في القصر.\r\n\r\nوندسور', 'Here you\'ll discover a lively town in a glorious riverside location with great shopping, restaurants and Windsor Castle - one of the Queen\'s official royal residences and the largest and oldest occupied castle in the world. If you’re lucky you’ll also see some of the local wildlife in the Great Park.', '', 'LONDON');
INSERT INTO `listings` VALUES ('17', 'City of dreaming spires. \r\n\r\nOxford. ', 'مدينة قمم الأحلام. \r\n\r\nأكسفورد ', 'Oxford is steeped in history and oozes character. For leisurely sightseeing, why don’t you take a trip on a punt (a traditional flat bottomed boat) or if you prefer to stick to dry land, take a hop-on and off bus tour. Fashion lovers (and bargain hunters) flock to nearby Bicester Village, a designer shopping outlet selling big names brands at discount prices', '', 'LONDON');
INSERT INTO `listings` VALUES ('18', 'A garden in full bloom.\r\n\r\nOxfordshire', null, 'Pack your picnic and plan a day out at Oxford’s Botanic Garden where there is always something interesting to see in the gardens.\r\nDon’t miss a trip to see the wide array of plants. The Gardens are separated into two areas, the Walled Garden and the Lower Garden, and both gardens have been planted to offer interest throughout the seasons.', '', 'LONDON');
INSERT INTO `listings` VALUES ('19', 'Enjoy the world’s best afternoon tea.\r\n\r\nLondon', 'استمتع بأفضل شاي ما بعد الظهيرة على مستوى العالم.\r\n\r\nلندن', 'Mmm…afternoon tea – finger sandwiches, dainty cakes and delights, not forgetting a large pot of fresh tea. You can tuck into this quintessentially British experience in all manner of beautiful locations around the UK – high class hotels, vintage tea rooms and stately manor houses.', '', 'LONDON');
INSERT INTO `listings` VALUES ('20', 'Blenheim Palace in full bloom.\r\n\r\nOxfordshire', null, 'Birthplace of Winston Churchill, Blenheim Palace is one of Britain\'s finest stately homes. It\'s surrounded by landscaped parkland, the handiwork of Capability Brown, and elegant formal gardens which make it an ideal place to explore on a sunny day. A triumph of romantic architecture, the palace is a World Heritage Site. ', '', 'LONDON');
INSERT INTO `listings` VALUES ('21', 'Take in one of Britain’s most beautiful streets.\r\n\r\nBath.', null, 'The Romans took advantage of the area’s natural hot springs by building the majestic Roman Baths, now a UNESCO heritage site. You can experience the mineral-rich waters for yourself at Bath Thermae Spa - don’t miss the spectacular views of the city from the rooftop pool and be sure to see one of the houses on Bath\'s famous Royal Crescent as it would have been in Georgian times.', '', 'LONDON');
INSERT INTO `listings` VALUES ('22', 'Mind the puddles.\r\n\r\nPeak District', 'انتبه للبركات الصغيرة.\r\n\r\nمرتفعات بيك ديستريكت (Peak District)', 'Take in stunning panoramas across dales and moors in the Peak District National Park. It is an area of contrasting natural beauty, with moors and dales, rivers, springs and caverns. The area is home to market towns, pretty villages, historic houses, famous attractions and hundreds of traditional events and loved by millions for its breath-taking views, relaxation, inspiration and adventure.\r\nTake in stunning panoramas across dales and moors in the Peak District National Park. It is an area of contrasting natural beauty, with moors and dales, rivers, springs and caverns. The area is home to market towns, pretty villages, historic houses, famous attractions and hundreds of traditional events and loved by millions for its breath-taking views, relaxation, inspiration and adventure.', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('23', 'Shopping in medieval Britain.\r\n\r\nYork.', 'تسوق في بريطانيا العصور الوسطى\r\n\r\nيورك', 'Like stepping back into the middle ages, the overhanging timber-framed houses and traditional shopfronts of The Shambles makes it one of the UK’s most historic (and picturesque) streets. A place of extraordinary cultural and historical wealth, this beautifully preserved medieval city is a must-visit! ', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('24', 'Go on an off-road adventure.\r\n\r\nLake District ', 'استمتع بالمغامرات على الطرق الممهدة والوعرة.\r\n\r\nليك ديستريكت (Lake District) ', 'It’s difficult to overstate the beauty of the Lake District.  \r\nThe area’s sparkling lakes, secret valleys and picturesque stone-built villages have captivated generations of visitors and inspired many famous artists. Sky-piercing peaks and rugged valleys overlook deep, glassy lakes in the UK’s largest national park. ', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('25', 'It\'s worth the hike! Snowdonia, North Wales', 'يا لها من نزهة رائعة! \r\n\r\nسنودونيا، شمال ويلز', 'One of Britain\'s best-known upland areas, Snowdonia, Wales, is famous for its slate, mountainous terrain and epic landscape of glacially sculpted valleys and craggy peaks. Take time out to hike, bike or simply enjoy the views from Wales\' tallest mountain, Snowdon.', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('26', 'Make a splash at Surf Snowdonia. North Wales', 'استمتع بالألعاب المائية في سيرف سنودونيا.\r\n\r\nشمال ويلز', 'Surf Snowdonia Adventure Park opens in early March 2017 and is a revolutionary world-first inland surf lagoon. Set in the lush, green Conwy Valley it’s fresh, wild and beautiful. The attraction is expected to add another wave of adventure to an already very compelling outdoor British destination.', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('27', 'Admire dancing daffodils. North Wales', null, 'The story of Wales is long and, at times, confusing. That would go some of the way towards explaining why the emblems of Wales include a dragon, a vegetable and a daffodil. The distinctive flowers bloom every spring, even after the harshest winters and bring with them the beginnings of a fresh season. ', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('28', 'Explore the beauty of Adlington Hall. Cheshire', null, 'There are so many fun things to do in Cheshire. Stroll around one of the region’s stunning stately homes and gardens for a perfect introduction to the county. Shop in Chester\'s elegant boutiques, tucked under crofts of medieval townhouses. Or head to market towns for local produce and tasty lunches.', '', 'MANCHESTER');
INSERT INTO `listings` VALUES ('29', 'Enjoy uninterrupted views of Yorkshire.', null, 'Looking for things to do in the Yorkshire Dales? Walk among patchwork green valleys, craggy cliff faces, and farmland laced with limestone walls. The hills are alive with the sound of wildlife – woodpeckers, cuckoos, and wood warblers. In August heather covers the moorland like a purple carpet. Follow the footsteps of Georgian gentry to spa towns like Harrogate to discover the pump rooms, manicured flower gardens, and quant tearooms.', '', 'MANCHESTER');
