/*
Navicat MySQL Data Transfer

Source Server         : Localhost
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : qatar2

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2017-02-28 19:16:06
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for listings
-- ----------------------------
DROP TABLE IF EXISTS `listings`;
CREATE TABLE `listings` (
  `id` mediumint(9) NOT NULL,
  `roll-over-description-english` varchar(150) DEFAULT NULL,
  `roll-over-description-arabic` varchar(150) DEFAULT NULL,
  `full-description-english` mediumtext,
  `full-description-arabic` mediumtext,
  `location` varchar(255) DEFAULT NULL,
  `posx` varchar(255) DEFAULT NULL,
  `posy` varchar(255) DEFAULT NULL,
  `markerSize` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of listings
-- ----------------------------
INSERT INTO `listings` VALUES ('0', 'Look into history. Stratford-upon-Avon.\r\n', 'انظر في أعماق التاريخ.\r\n\r\nستراتفورد أبون آفون\r\n', 'Immerse yourself in everything Shakespeare in Stratford-upon-Avon. Built on the banks of the Avon River is best known as the birthplace of William Shakespeare and is subsequently the home of The Royal Shakespeare Company.', 'اغمر نفسك في عالم شكسبير في ستراتفورد أبون آفون. استمتع بزيارة مسقط رأس ويليام شكسبير المشيدة على ضفاف نهر آفون، والتي أصبحت لاحقاً مقراً لشركة شكسبير الملكية. ', 'Birmingham', '47', '52', 'small');
INSERT INTO `listings` VALUES ('1', 'Curious countryside cottages. \r\n\r\nCotswolds.', 'بيوت ريفية صغيرة رائعة. \r\n\r\nكوتسوولدز (Cotswolds).\r\n', 'Explore villages made of honey-coloured stone and see why this area is picture-postcard England at its most enchanting. It\'s a favourite getaway for British celebrities so excellent food and luxury places to stay abound. Be sure to enjoy a picnic by the brook in Castle Combe, one of Britain\'s prettiest villages.', 'استكشف القرى المصنوعة من الحجارة ذات اللون العسلي وتعرف على أسباب كون هذه المنطقة إحدى أكثر الأماكن سحراً وبهاءً في إنجلترا. إنها الوجهة المفضَّلة لمشاهير بريطانيا حيث تكثر بها المطاعم والأماكن الفاخرة. استمتع بأخذ نزهة مائية إلى قلعة كامْبْ (Castle Combe)؛ واحدة من أجمل القرى في بريطانيا.', 'Birmingham', '50', '42', 'small');
INSERT INTO `listings` VALUES ('3', 'Fields of bluebells.\r\n\r\nWarwickshire.', 'حقول الجريس\r\n\r\nوورويكشاير\r\n', 'Visit Warwickshire to revel in the heart of Shakespeare\'s England. See signature motte-and-bailey forts and romantic Elizabethan architecture. Miles of canals and stairway locks beckon you for lazy lunches and picnics. A visit in springtime will almost certainly guarantee the pleasure of seeing carpets of delicately scented bluebells throughout ancient woodlands.', 'تفضل بزيارة وورويكشاير للاستمتاع بقلب إنجلترا الواردة في أعمال شكسبير. استمتع برؤية الحصون الحجرية والخشبية المسوّرة والمحصنة والطراز المعماري الرومانسي الذي يعود إلى العصر الإليزابيثي. بالإضافة إلى ذلك، هناك أميال من القنوات وأقفال الدرج التي تغويك بالجلوس لتناول الغذاء والخروج في نزهات لا مثيل لها. ومن المؤكد أن الزيارة في موسم الربيع سوف تضمن لك بكل تأكيد متعة رؤية الأرض تفترشها نباتات الجريس العطرية التي تفوح منها أذكى الروائح في كافة أنحاء الغابات القديمة.', 'Birmingham', '54', '46', 'small');
INSERT INTO `listings` VALUES ('4', 'Beautiful blossom. \r\nBatsford Arboretum, Gloucestershire.', 'زهور جميلة \r\nمشتل باتسفورد، جلوسيسترشاير\r\n', 'Elegant spa and market towns and stately homes presiding over rolling, green landscapes are a plenty in Gloucestershire. However, Batsford Arboretum is a must see for nature lovers and is home to a whole host of flora and fauna. There is a lovely annual programme of events – from outdoor theatre productions under the arboretum tree canopy to gardening themed talks and special events.', 'ما في جلوسيسترشاير فسوف تجد الكثير من مراكز سبا الرائعة والبلدات التي تقام فيها الأسواق المركزية إضافة إلى القصورة الريفية الفاخرة التي تطل على مناظر طبيعية خضراء تلف المكان بأسره.  وبالنسبة لعشاق الطبيعية، فلا يمكن أن يفوتهم مشاهدة مشتل باتسفورد (Batsford Arboretum)، والذي يعد أيضاً مقراً لمجموعة كاملة من النباتات والحيوانات. ونود أن نشير إلى توافر برنامج سنوي رائع من الفعاليات - بدءاً من الإنتاج المسرحي في الهواء الطلق في ظلال أشجار المشاتل المدهشة وصولاً إلى الاجتماعات التي تكتنفها الخضرة من كل مكان والفعاليات الخاصة.', 'Birmingham', '45', '48', 'small');
INSERT INTO `listings` VALUES ('5', 'Be enchanted by Festival No. 6.\r\nPortmeirion', 'استمتع بسحر المهرجان رقم 6 (FESTIVAL No.6)\r\nبورتميريون\r\n', 'You\'ll be forgiven for wondering if you\'re in Britain when you arrive in Portmeirion. With its cliff-top location and Italianate white-washed buildings, it\'s often compared to a Mediterranean village, but the spectacular coastal views are 100% Welsh. Visit when Festival No 6 is on and see comedy shows, film previews and some of the most exciting musicians from around the world.', 'سوف تتملكك الدهشة تماماً وتتساءل إذا ما كنت في بريطانيا عند الوصول إلى بورتميريون، ولكننا سنغفر لك ذلك. فمع موقعها على قمة الجروف الصخرية الشاهقة ومبانيها البيضاء المشيدة على الطراز الإيطالي، فغالباً ما يتم مقارنتها بقرى البحر المتوسط، غير أن المشاهدة الساحلية الخلابة هي مشاهد ويلزية بنسبة 100%.  تفضل بالزيارة أثناء انعقاد المهرجان رقم 6 (FESTIVAL No.6)واستمتع بالعروض الكوميدية ومشاهدة العروض الخاصة للأفلام، إضافةً إلى بعض أفضل الموسيقيين من مختلف أنحاء العالم.', 'Birmingham', '42', '15', 'small');
INSERT INTO `listings` VALUES ('6', 'A view worth every step.\r\n\r\nEdinburgh. ', 'هناك مشهد يستحق الإطلالة عليه في كل خطوة.\r\n\r\nإدنبره \r\n', 'The capital of Scotland makes an unforgettable impression with its historic, hilly landscape. Before you head out to the beautiful landscapes of Scotland’s countryside, spend the day in its capital city, Edinburgh. It’s known for its world-class festivals and the cityscapes of its Old and New Towns form a UNESCO World Heritage site. There’s plenty of green space within the city too; at its heart is Holyrood Park with three lochs, wildlife and Arthur’s Seat, an extinct volcano, to explore. The Royal Botanic Garden is another green oasis in the city.', 'سوف تترك عاصمة اسكتلندا في ذاكرتك انطباعاً لا يُنسى بتاريخها وتلالها ذات المناظر الطبيعية الرائعة. قبل أن تخرج قاصداً معالم الريف الاسكتلندي الجميل، اقض يوماً في عاصمتها إدنبره. وهي مشهورة بمهرجاناتها العالمية فضلاً عن المعالم الحضرية للبلدات القديمة والجديدة التي تندرج ضمن تصنيف مواقع التراث العالمي حسب اليونسكو. ثمة مساحات وافرة من الخضرة داخل المدينة أيضاً، وفي القلب منها حديقة هوليرود بارك (Holyrood Park) مع ثلاث بحيرات إضافة إلى الحياة البرية، ومقعد أرثر (Arthur’s Seat)، وهو بركان خامد، كل هذا يتيح فرصة ذهبية لإمتاع العين والروح. الحديقة النباتية الملكية هي واحة أخرى خضراء في المدينة.', 'Edingburgh', '36', '8', 'small');
INSERT INTO `listings` VALUES ('7', 'Steaming across 21 arches of magical history.\r\n\r\nGlenfinnan Viaduct', 'استمتع بركوب القطار البخاري الذي يمر عبر 21 قنطرة متجذرة في أعماق التاريخ.\r\n\r\nجسر جلينفينان (Glenfinnan Viaduct)\r\n', 'For a truly magical experience, board the legendary Jacobite Steam Train and chug across the world-famous 21-arched Glenfinnan Viaduct and through some of the most beautiful and storied countryside in the world. The area is renowned for its beauty as well as its historic significance. \r\n\r\nFor a truly magical experience, board the legendary Jacobite Steam Train and chug across the world-famous 21-arched Glenfinnan Viaduct and through some of the most beautiful and storied countryside in the world. The area is renowned for its beauty as well as its historic significance.', 'ومن أجل الاستمتاع بتجربة ساحرة، يمكنك أن تركب قطار جاكوبايت البخاري الأسطوري وتشق الطريق عبر جسر جلينفينان العالمي الشهير ذي الواحد وعشرين قوساً وسط أجمل ريف في العالم، فالمنطقة مشهورة بجمالها وقيمتها التاريخية أيضاً. ', 'Edingburgh', '36', '1', 'large');
INSERT INTO `listings` VALUES ('8', 'The land of myths and legends.\r\n\r\nEilean Donan Castle', 'أرض الأساطير والخرافات.\r\n\r\nقلعة إيليان دونان\r\n', 'You won’t be able to stop gazing out of the windows if you stay in the luxurious Eilean Donan Cottage. It has uninterrupted views across the water to a sight you’ll more than likely already recognise: the 13th-century Eilean Donan castle, standing on an island where three sea lochs meet and connected to the shore by a stern stone bridge. It’s one of the most iconic images of Scotland.', 'لن تكون قادراً على التوقف عن التحديق في النوافذ في حال إقامتم في كوخ إيليان دونان الفاخر (Eilean Donan Cottage). إنه له إطلالات يصعب التعبير عن جمالها عبر المياه ترى من خلالها ما لا يسع الخيال نفسه التعبير عنه كقلعة إيليان دونان التي يعود تاريخها إلى القرن الثالث عشر والتي تقف على جزيرة تلتقي فيها البحيراث الثلاث بالشاطئ عند جسر حجري عتيد. إنها واحدة من أحسن الصور المذهلة في اسكتلندا.', 'Edingburgh', '45', '9', 'small');
INSERT INTO `listings` VALUES ('9', 'A view worth every step.\r\n\r\nEdinburgh.', 'مغامرات أعلى الأشجار. \r\n\r\nغابة جلينتريس\r\n', 'Climb to the highest point in the city. The reward as you stand at the top of 244 metre Arthur’s Seat after a hike through Holyrood Park is the sight of Edinburgh’s castle, crescents and spires mapped out all around you, and beyond to the Forth Bridge, the east coast and the Highlands. Pick up a picnic from one of Edinburgh’s fine food delis for the journey. ', 'تسلق إلى أعلى نقطة في المدينة، واستمتع عند الوقوف أعلى مقعد أرثر الذي يبلغ ارتفاعه 244 متراً بعد الصعود إليه عبر هوليرود بارك (Holyrood Park) بمشهد  قلعة إدنبره، والأهلَّة والأبراج التي تلوح من حولك، ثم تنظر من بعيد إلى جسر فورث بريدج والساحل الشرقي والمرتفعات. اختر واحداً من الأطعمة اللذيذة التي تشتهر بها إدنبره للاستمتاع برحلة رائعة. ', 'Edingburgh', '40', '14', 'small');
INSERT INTO `listings` VALUES ('10', 'Treetop adventures. \r\n\r\nGlentress Forest', 'مغامرات أعلى الأشجار. \r\n\r\nغابة جلينتريس\r\n', 'Looking for some active fun? Designed to entertain tarzans big and small, expect to traverse the tree canopy on zip wires and aerial walkways. At Go Ape, explore the forest from high up on a Tree Top Adventure – swing through the trees, zoom down zip wires and tackle high rope crossings whilst enjoying the amazing views of one of Scotland’s amazing natural environments. ', 'هل تبحث عن الترفيه الذي لا يخلو من المتعة والإثارة؟ استمتع بهذا المكان الذي تم تصميمه لتقديم المتعة والإثارة والترفيه إلى الجميع من الصغار إلى الكبار بشكل يشبه شخصية طرازان، فمن المتوقع هنا أن تجتاز حواجز الأشجار من خلال \"زيب لاين\" وعبر الممرات الهوائية. هنا في جو آب (Go Ape)، استكشف الغابة من الأعلى من خلال مغامرة أعلى الأشجار - تأرجح وتمايل بين الأشجار، واستمتع بالتدلي من \"زيب لاين\" مع الاستمتاع بمناظر رائعة لواحدة من أجمل وأروع البيئات الطبيعية في اسكتلندا. ', 'Edingburgh', '42', '5', 'small');
INSERT INTO `listings` VALUES ('11', 'Attempt archery in the great outdoors.\r\nScottish Highlands', 'جرب ممارسة الرماية في الهواء الطلق.\r\nالمرتفعات الاسكتلندية\r\n', 'You’ll require both skill and a steady hand to strike gold in this fun field sport. Archery is an ancient and elegant pastime which is a ‘must do’ activity for everybody for some friendly competition. Prepare your bow and arrow, pull back and shoot all whilst testing your hand-to-eye coordination as you practice and develop your ability.', 'ستكون بحاجة للجمع ما بين المهارة وقوة الأيدي من أجل الفوز في هذه الرياضة الميدانية الرائعة، فالرماية هي إحدى متع الترفيه القديمة والأنيقة، والتي كانت تعد نشاطاً \"يجب أن يفعله\" كل شخص من أجل خوض غمار التنافس الودي. جهّز قوسك وسهمك، اسحب السهم للوراء وأطلقه، كل ذلك مع ضرورة التوافق بين الأيدي والعين أثناء ممارسة الرمي من أجل تطوير قدراتك.', 'Edingburgh', '33', '1', 'small');
INSERT INTO `listings` VALUES ('12', 'Scenery to take your breath away. Loch Ness, Inverness', 'مشهد يحبس الأنفاس. بحيرة نيس، إنفرنيس', 'There are many fantastic facts, stories and legends about Loch Ness: it holds more fresh water than all the lakes in England and Wales combined; its waters never freeze over; and it’s the home of the Loch Ness Monster. It’s also incredibly beautiful, so take a moment to simply take in the views. By foot or by boat, the possibilities for adventure around Inverness and Loch Ness are never-ending.', 'ثمة العديد من الحقائق المذهلة والقصص والحكايات الأسطورية المثيرة عن بحيرة نيس التي تحتوي على مياه عذبة أكثر من كل البحيرات في إنجلترا وويلز مجتمعين، فمياهها لا تتجمد أبداً، وهي موطن ما يُعرف بوحش بحيرة نيس. إنها ساحرة الجمال، فلا تبخل على نفسك بلحظات تغوص فيها في روعتها وإطلالاتها، فخوض المغامرات الرائعة التي لا تُحصى ولا تُعد حول إنفرنيس وبحيرة نيس أمر لا يتوقف أبداً سواءً سيراً على الأقدام أو من خلال القارب.', 'Edingburgh', '36', '14', 'small');
INSERT INTO `listings` VALUES ('13', 'Hear the band in full swing.\r\n\r\nEdinburgh', 'استمع إلى الفرقة الموسيقية في قمة أدائها. \r\n\r\nإدنبره\r\n', 'Bringing together grand spectacle, fantastic music and Scottish heritage, the annual Royal Military Tattoo at Edinburgh Castle is a major summer event showcasing some of the best traditional and military drumming and piping around. There are bands with polished trumpets and crisp uniforms, cultural dance troupes, singers, and a grand display of fireworks at the end of every Saturday performance. ', 'يجمع العرض العسكري الملكي السنوي في إدنبره ما بين روعة المنظر وجمال الموسيقى فضلاً عن التراث الاسكتلندي، فهو أحد الفعاليات الصيفية الكبرى الذي يلقي الضوء على بعض أفضل أنواع موسيقى الطبول والمزمار التقليدية والعسكرية. يضم هذا العرض العديد من الفرق الموسيقية بأزيائها المموجة وأبواقها البولندية، وفرق الرقص، والمغنيين، إضافةً إلى عرض كبير للألعاب النارية في نهاية العرض كل يوم سبت.  ', 'Edingburgh', '66', '58', 'large');
INSERT INTO `listings` VALUES ('14', 'Make a splash in the city. \r\n\r\nLondon.', 'استمتع بالألعاب المائية في المدينة. \r\n\r\nلندن.\r\n', 'In London you can marvel at the city’s many iconic buildings and palaces, immerse yourself in culture at one of the 170 museums and relax amidst the natural beauty of the Royal Parks. Take a spin on the London Eye to experience spectacular views of the city\'s skyline and get a unique perspective on iconic London landmarks like Big Ben and Westminster Abbey.', 'في لندن، سوف تستمتع بالعديد من المباني والأماكن البارزة والرائعة، لذا اغمر كافة حواسك بجوها الثقافي عبر 170 متحفاً تاريخياً واسترخ وسط جمال الطبيعة في المتنزهات الملكية. ألق نظرة على عين لندن للاستمتاع بمشاهدة المناظر الخلابة للمدينة، واستمتع بتجربة فريدة عند مشاهدة معالم لندن التاريخية مثل ساعة بيج بين ودير ويستمنستر.', 'London', '62', '58', 'small');
INSERT INTO `listings` VALUES ('15', 'Discover theatre in the Queen’s Gardens. \r\n\r\nLondon.', 'استكشف المسرح في حدائق الملكة. \r\n\r\nلندن.\r\n', 'Did you know there are more than 230 theatres in London? Watch a musical in the West End or try something different and head to one of the few outdoor theatres such as Regent’s Park Open Air Theatre. Established in 1932, it is one of the largest theatres in London and hosts an extensive run of summertime plays under the stars.  ', 'هل تعلم أن هناك ما يزيد عن 230 مسرحاً في لندن؟ استمتع بمشاهدة الموسيقى الغنائية في ويست إند وجرب شيئاً مختلفاً، أو توجه إلى أحد المسارح المشيدة في الهواء الطلق مثل المسرح المفتوح في ريجينت بارك. تجدر الإشارة إلى أن هذا المسرح قد تم بناؤه في عام 1932، ويعدا واحداً من أكبر المسارح في لندن، ويستضيف مجموعة كبيرة من العروض المسرحية التي تقام في فصل الصيف تحت سحر النجوم.  ', 'London', '59', '57', 'small');
INSERT INTO `listings` VALUES ('16', 'Rush Hour at the Palace.\r\n\r\nWindsor', 'ساعة الذروة في القصر.\r\n\r\nوندسور\r\n', 'Here you\'ll discover a lively town in a glorious riverside location with great shopping, restaurants and Windsor Castle - one of the Queen\'s official royal residences and the largest and oldest occupied castle in the world. If you’re lucky you’ll also see some of the local wildlife in the Great Park.', 'هنا سوف تستكشف مدينة نابضة بالحياة على ضفاف أحد الأنهار الرائعة، والتي تزخر بالعديد من أماكن التسوق الكبيرة والمطاعم إضافة إلى قلعة وندسور، والتي تعد واحدة من المقرات الملكية الرسمية للملكة وأكبر وأقدم قلعة محتلة في العالم. وإذا كنت محظوظاً، فسوف تسعد برؤية بعض معالم الحياة البرية المحلية في المتنزه الكبير (Great Park).', 'London', '54', '55', 'small');
INSERT INTO `listings` VALUES ('17', 'City of dreaming spires. \r\n\r\nOxford. ', 'مدينة قمم الأحلام. \r\n\r\nأكسفورد \r\n', 'Oxford is steeped in history and oozes character. For leisurely sightseeing, why don’t you take a trip on a punt (a traditional flat bottomed boat) or if you prefer to stick to dry land, take a hop-on and off bus tour. Fashion lovers (and bargain hunters) flock to nearby Bicester Village, a designer shopping outlet selling big names brands at discount prices', 'تضرب أكسفورد بجذورها في أعماق التاريخ، وإذا كنت ترغب في مشاهدة ممتعة لمعالم المدينة، لماذا لا تأخذ جولة على متن قارب البنط (قارب تقليدي مسطح من الأسفل)، أو إذا كنت تفضل القيام بذلك عبر طرقات المدينة، يمكنك أخذ جولة عبر حافلات النقل الحر. أما عشاق الموضة (وقناصي الصفقات) فيمكنهم التوجه إلى قرية بيسستر القريبة (Bicester Village)، وهي منفذ تسوق رائع لكبار المصممين، حيث تقوم ببيع العلامات التجارية الكبيرة بأسعار مخفضة.', 'London', '53', '60', 'small');
INSERT INTO `listings` VALUES ('18', 'A garden in full bloom.\r\n\r\nOxfordshire', 'حديقة مليئة بالورود والأزهار.\r\n\r\nأكسفوردشاير\r\n', 'Pack your picnic and plan a day out at Oxford’s Botanic Garden where there is always something interesting to see in the gardens.\r\nDon’t miss a trip to see the wide array of plants. The Gardens are separated into two areas, the Walled Garden and the Lower Garden, and both gardens have been planted to offer interest throughout the seasons.', 'حدد نزهتك وخطط لقضاء يوم رائع في حديقة أكسفورد النباتية، حيث دائماً ما يوجد هناك شيء ما شيق في الحدائق يستحق الرؤية،\r\nهنا سوف تستمتع برؤية مجموعة كبيرة من النباتات. تجدر الإشارة إلى أن الحدائق مقسمة إلى منطقتين هما: الحديقة المُسوّرة (Walled Garden) والحديقة السفلية (Lower Garden)؛ حيث تم زرع كلا الحديقتين من أجل توفير إطلالة رائعة ومذهلة لهما في كل المواسم.\r\n', 'London', '68', '51', 'large');
INSERT INTO `listings` VALUES ('19', 'Enjoy the world’s best afternoon tea.\r\n\r\nLondon', 'استمتع بأفضل شاي ما بعد الظهيرة على مستوى العالم.\r\n\r\nلندن\r\n', 'Mmm…afternoon tea – finger sandwiches, dainty cakes and delights, not forgetting a large pot of fresh tea. You can tuck into this quintessentially British experience in all manner of beautiful locations around the UK – high class hotels, vintage tea rooms and stately manor houses.', 'لا تنس...شاي ما بعد الظهيرة - الساندوتشات الخفيفة والكعك اللذيذ والأطعمة الشهية، ناهيك عن إبريق كبير من الشاي الطازج. يمكنك الانغماس في هذه التجربة البريطانية الأصيلة بالطريقة التي تعجبك في مختلف الأماكن الجميلة في كافة أنحاء المملكة المتحدة - مثل الفنادق الفاخرة، صالات ومطاعم الشاي الكلاسيكية الصغيرة والقصور الريفية الرائعة.', 'London', '68', '51', 'large');
INSERT INTO `listings` VALUES ('20', 'Blenheim Palace in full bloom.\r\n\r\nOxfordshire', 'قصر بلنهايم المليء بالورود والأزهار.\r\n\r\nأكسفوردشاير\r\n', 'Birthplace of Winston Churchill, Blenheim Palace is one of Britain\'s finest stately homes. It\'s surrounded by landscaped parkland, the handiwork of Capability Brown, and elegant formal gardens which make it an ideal place to explore on a sunny day. A triumph of romantic architecture, the palace is a World Heritage Site. ', 'يُعد قصر بلينهايم أحد أروع المنازل البريطانية المصممة بقمة الذوق الرفيع، وهو مسقط رأس وينستون تشرتشيل. هذا القصر مُحاطٌ بمتنزه مشذب الأشجار، ناهيك عن الأعمال اليدوية من إبداع الفنان كابابيلتي براون، والحدائق الرسمية الأنيقة التي تجعل منه مكاناً مثالياً لارتياده في يوم مشمس. ونظرًا لكونه صرحًا معماريًا للرومانسية، يُعتبر القصر من مواقع التراث العالمي. ', 'London', '48', '58', 'large');
INSERT INTO `listings` VALUES ('21', 'Take in one of Britain’s most beautiful streets.\r\n\r\nBath.', 'استمتع بالتجول في أحد أجمل الشوارع البريطانية.\r\n\r\nباث.\r\n', 'The Romans took advantage of the area’s natural hot springs by building the majestic Roman Baths, now a UNESCO heritage site. You can experience the mineral-rich waters for yourself at Bath Thermae Spa - don’t miss the spectacular views of the city from the rooftop pool and be sure to see one of the houses on Bath\'s famous Royal Crescent as it would have been in Georgian times.', 'استفاد الرومان من الينابيع الطبيعية الساخنة في المدينة وقاموا بتشييد الحمامات الرومانية الرائعة، والمدرجة الآن ضمن مواقع التراث العالمي التابعة لليونسكو. استكشف بنفسك المياه الغنية بالمعادن في منتجع باث ثيرما سبا (Bath Thermae Spa) - ولا تُفوت مناظر الإطلالات الخلابة للمدينة من حوض السباحة الموجود على السطح، وتأكد من رؤية أحد المنازل الموجودة على الهلال الملكي الشهير في باث كما لو كان موجوداً العصر الجورجي.', 'London', '68', '51', 'large');
INSERT INTO `listings` VALUES ('22', 'Mind the puddles.\r\n\r\nPeak District', 'انتبه للبركات الصغيرة.\r\n\r\nمرتفعات بيك ديستريكت (Peak District)\r\n', 'Take in stunning panoramas across dales and moors in the Peak District National Park. It is an area of contrasting natural beauty, with moors and dales, rivers, springs and caverns. The area is home to market towns, pretty villages, historic houses, famous attractions and hundreds of traditional events and loved by millions for its breath-taking views, relaxation, inspiration and adventure.\r\nTake in stunning panoramas across dales and moors in the Peak District National Park. It is an area of contrasting natural beauty, with moors and dales, rivers, springs and caverns. The area is home to market towns, pretty villages, historic houses, famous attractions and hundreds of traditional events and loved by millions for its breath-taking views, relaxation, inspiration and adventure.', 'تجول وسط المناظر البانورامية الخلابة وسط الوديان والسبخات في متنزه ليك ديستريكت الوطني (Peak District National Park)، إنها منطقة ذات جمال طبيعي متباين، تكتنفها السبخات والوديان والأنهار والينابيع والمغارات. كما تنتشر بالمنطقة البلدات ذات الأسواق المركزية والقرى الجميلة والمنازل التاريخية ومعالم الجذب الشهيرة ومئات الفعاليات التقليدية، مما يجعلها قبلة الملايين بإطلالاتها التي تحبس الأنفاس، ووسائل الاستجمام والراحة المتوافرة بها، إضافةً إلى كونها مصدراً للإلهام والمغامرات الرائعة.', 'Manchester', '58', '28', 'small');
INSERT INTO `listings` VALUES ('23', 'Shopping in medieval Britain.\r\n\r\nYork.', 'تسوق في بريطانيا العصور الوسطى\r\n\r\nيورك\r\n', 'Like stepping back into the middle ages, the overhanging timber-framed houses and traditional shopfronts of The Shambles makes it one of the UK’s most historic (and picturesque) streets. A place of extraordinary cultural and historical wealth, this beautifully preserved medieval city is a must-visit! ', 'إن التجول وسط المنازل ذات الهياكل الخشبية المعلقة وواجهات المحلات التقليدية لشارع شامبلز (The Shambles) - كما لو كنت قد عدت إلى العصور الوسطى - يجعل من هذا الشارع أحد أهم الشوارع التاريخية في المملكة المتحدة. إن هذا المكان الذي يزخر بثروة تاريخية وثقافية هائلة يجعل من زيارة هذه المدينة الجميلة التي تعود إلى العصور الوسطى والتي تم الحفاظ على معالمها أمراً لا غنى عنه.  ', 'Manchester', '40', '25', 'small');
INSERT INTO `listings` VALUES ('24', 'Go on an off-road adventure.\r\n\r\nLake District ', 'استمتع بالمغامرات على الطرق الممهدة والوعرة.\r\n\r\nليك ديستريكت (Lake District) \r\n', 'It’s difficult to overstate the beauty of the Lake District.  \r\nThe area’s sparkling lakes, secret valleys and picturesque stone-built villages have captivated generations of visitors and inspired many famous artists. Sky-piercing peaks and rugged valleys overlook deep, glassy lakes in the UK’s largest national park. ', 'إنه من الصعوبة بمكان المبالغة في جمال ليك ديستريكت (Lake District)،  \r\nفبحيراتها المتألقة، ووديانها السرية، وقراها المبنية من الأحجار ذات الألوان الرائعة خطفت قلوب أجيالٍ من الزائرين وألهمت العديد من أشهر الفنانين. كما أن قممها التي تلامس السماء ووديانها الوعرة تطل على بحيراتها العميقة والشفافة في أكبر متنزه وطني بالمملكة المتحدة. \r\n', 'Manchester', '41', '47', 'small');
INSERT INTO `listings` VALUES ('25', 'It\'s worth the hike! Snowdonia, North Wales', 'يا لها من نزهة رائعة! \r\n\r\nسنودونيا، شمال ويلز\r\n', 'One of Britain\'s best-known upland areas, Snowdonia, Wales, is famous for its slate, mountainous terrain and epic landscape of glacially sculpted valleys and craggy peaks. Take time out to hike, bike or simply enjoy the views from Wales\' tallest mountain, Snowdon.', 'تعد سنودونيا في ويلز واحدة من أشهر المناطق المرتفعة في بريطانيا والتي تشتهر بتضاريسها الجبلية ذات الصخور الإرودازية فضلاً عن المناظر الطبيعية الملحمية لوديانها الثلجية المنحوتة وقممها ذات الأجراف المتحدرة. استمتع بوقتك في التنزه على القدمين أو بركوب الدراجة أو استمتع بالمناظر الخلابة من الجبل الأكثر ارتفاعاً في ويلز، وهو جبل سنودون. ', 'Manchester', '34', '42', 'small');
INSERT INTO `listings` VALUES ('26', 'Make a splash at Surf Snowdonia. North Wales', 'استمتع بالألعاب المائية في سيرف سنودونيا.\r\n\r\nشمال ويلز\r\n', 'Surf Snowdonia Adventure Park opens in early March 2017 and is a revolutionary world-first inland surf lagoon. Set in the lush, green Conwy Valley it’s fresh, wild and beautiful. The attraction is expected to add another wave of adventure to an already very compelling outdoor British destination.', 'يفتح متنزه \"سيرف سنودونيا أدفينشر بارك\" للألعاب المائية أبوابه في مطلع مارس 2017، وهو أول بحيرة داخلية من نوعها في العالم للألعاب المائية وركوب الأمواج. انطلق من وادي كونوي (Conwy Valley) الخصب الأخضر بجماله ونضارته وحياته البرية. ومن المتوقع أن يضيف هذا المعلم موجة أخرى من المغامرات إلى هذه الوجهة البريطانية التي تزخر بالفعل بالعديد من الأنشطة التي تقام في الهواء الطلق. ', 'Manchester', '46', '48', 'small');
INSERT INTO `listings` VALUES ('27', 'Admire dancing daffodils. North Wales', 'استمتع بالنرجس البري الراقص \r\n\r\nشمال ويلز\r\n', 'The story of Wales is long and, at times, confusing. That would go some of the way towards explaining why the emblems of Wales include a dragon, a vegetable and a daffodil. The distinctive flowers bloom every spring, even after the harshest winters and bring with them the beginnings of a fresh season. ', 'قصة ويلز طويلة، بل إنها محيرة في بعض الأوقات، وربما يشرح هذا بعضٍ من أسباب إدراج ديناصور وخضروات ونبات النرجس البري الأصفر في شعار ويلز. تتفتح الأزهار الرائعة في كل ربيع حتى بعد هطور الأمطار الغزيرة في الشتاء، وتجلب معها بداية موسم رائع تكتنفه النضارة والجمال والورود. ', 'Manchester', '43', '37', 'small');
INSERT INTO `listings` VALUES ('28', 'Explore the beauty of Adlington Hall. Cheshire', 'استكشف جمال قاعة أدلينجتون (Adlington Hall).\r\n\r\nتشيشاير\r\n', 'There are so many fun things to do in Cheshire. Stroll around one of the region’s stunning stately homes and gardens for a perfect introduction to the county. Shop in Chester\'s elegant boutiques, tucked under crofts of medieval townhouses. Or head to market towns for local produce and tasty lunches.', 'هناك العديد من الأمور الترفيهية الممتعة التي يمكنك القيام بها في تشيشاير. تجول حول واحدٍ من أجمل القصور والحدائق الريفية الفاخرة من أجل التعرف على المنطقة بشكل مثالي. تسوق في متاجر تشيشارير الجميلة، الموجودة أسفل مزارع المنازل الصغيرة (تاون هاوس) التي تعود إلى العصور الوسطى.  أو توجه إلى البلدات ذات الأسواق الكبيرة من أجل الحصول على المنتجات المحليات وتذوق أشهى المأكولات.', 'Manchester', '51', '18', 'small');
INSERT INTO `listings` VALUES ('29', 'Enjoy uninterrupted views of Yorkshire.', 'استمتع بمناظر رائعة لا نهاية لها في يوركشاير. ', 'Looking for things to do in the Yorkshire Dales? Walk among patchwork green valleys, craggy cliff faces, and farmland laced with limestone walls. The hills are alive with the sound of wildlife – woodpeckers, cuckoos, and wood warblers. In August heather covers the moorland like a purple carpet. Follow the footsteps of Georgian gentry to spa towns like Harrogate to discover the pump rooms, manicured flower gardens, and quant tearooms.', 'هل تبحث عن أشياء للقيام بها في وديان يوركشاير؟ تجول وسط الوديان الخضراء وواجهات الجروف المتحدرة والمزارع المحاطة بأسوار من الأحجار الجيرية. أما التلال فتنبض بالحياة البرية - طيور القراع (أو نقار الخشب)، وطيور الوَقْواق وطيور نقشارة الغاب. وفي أغسطس، يغطي نبات الخَلَنْج أراضي المستنقعات لتبدو مثل السجادة ذات اللون الأرجواني. تتبع آثار أقدام الطبقة الطبقة الأرستقراطية الجورجية في حمامات سبا مثل هاروجيت (Harrogate) لاستكشاف غرف المضخات، وحدائق الأزهار المشذبة، وقاعات الشاي الأنيقة.', 'Manchester', '58', '28', 'small');

-- ----------------------------
-- Table structure for register
-- ----------------------------
DROP TABLE IF EXISTS `register`;
CREATE TABLE `register` (
  `firstName` varchar(255) DEFAULT NULL,
  `surname` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `flyingFrom` varchar(255) DEFAULT NULL,
  `hasShared` varchar(255) DEFAULT NULL,
  `items` varchar(255) DEFAULT NULL,
  `sessionId` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of register
-- ----------------------------
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '0,1,4,5,7,8,22,26', 'k3mmk12ks3h7s42u6hn9csmp1jt66jev');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '0,4,6,7,10', 're6a2fgpmvckum0g1lq2ld3105t7u43s');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'UK', null, '2,4,22,25,26', 'vu24cvm9obs15el6kjsj93l5lma655jk');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'UK', null, '2,4,7,8', 'moqk6cpb201fqtid7p9njku40j7vaklk');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '0,2,3,6,7', '4shpvbj8nonhh3ft25095q14s2qe820b');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '4,7,8,23', 'pp349b3ai0sufbrmhrgsl1k97vh3isol');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'UK', null, '0,1,4,5,6,7,8', '60qvg1pd8429flvrandqgpof8l6ksm7o');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '2,3,5,6,8', 'tgrv9janjpdkqlm83ej84u12hakm6etn');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '0,2,5,6,7', 'jg9a53l6si4epmq9j5pbd4dik87mvi3l');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '1,2,4,8,26', 'poceq4jc7bg8qmfdk1opo7eq56m1e6vf');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '2,3,4,6,8,13', 'v491ajs9rktbb3nm1r6ingi4hadrk4fo');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', null, null, null, 'l9j3oue8li6a3h5sfpm4gfd677l6qfn7');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', null, null, null, 'qs58b4ml8ikkt9f3sp10891jrdlccj1j');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'Dubai', null, '0,2,4,6', 'h7p9qjquut28f2al6b19la4pjqq665kj');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', null, null, null, 'd5734b14911d2b5e32af109ee4b0cc6a4e3f6a32');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'UK', null, '1,3,4,5,6,8', 'foh3isf01cnooj3045bq442qjqs4sa67');
INSERT INTO `register` VALUES ('Rob', 'Lone', 'info@fusionrobotdesign.com', 'UK', null, '0,1,2,4,5', 'm59vo09d7tdgjbch6hpksntnpds7v06e');
SET FOREIGN_KEY_CHECKS=1;
